In [183]:
import pandas as pd
data= [1,2,3,4,5]
#1D data (1 column data)
series= pd.Series(data)
print("Series: \n" ,series)
print(type(series))

Series:
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [184]:
# Create series from dictionary

data= {
    'a':1,
    'b':2,
    'c':3
}
series_dic=pd.Series(data)
print(series_dic)

a    1
b    2
c    3
dtype: int64

In [185]:
data=[10,20,30]
index=["a",'b','c']
pd.Series(data,index)

a    10
b    20
c    30
dtype: int64

In [186]:
# Data Frame  (2D data like table)
# Create dataframe from a dictionry of list
data= {
    "Name":["Kulvinder","Herry","Jack"],
    "Age":[26,24,34],
    'city':["Lahore","Reading","London"]
    
}
df=pd.DataFrame(data)
print(df)
print(type(df))

        Name  Age     city
0  Kulvinder   26   Lahore
1      Herry   24  Reading
2       Jack   34   London
<class 'pandas.core.frame.DataFrame'>

In [187]:
import numpy as np
np.array(df)

array([['Kulvinder', 26, 'Lahore'],
       ['Herry', 24, 'Reading'],
       ['Jack', 34, 'London']], dtype=object)

In [188]:
# Create df from list of dictionaries
data = [

      { "Name":"Kulvinder","Age":26,"city":"Lahore"},
      { "Name":"Herry","Age":33,"city":"Reading"},
      { "Name":"Jack","Age":24,"city":"London"},
    
]


df=pd.DataFrame(data)
print(df)

        Name  Age     city
0  Kulvinder   26   Lahore
1      Herry   33  Reading
2       Jack   24   London

In [189]:
# df =pd.read_csv("sales_data.csv")
# df.head(5)

In [190]:
df.tail(5)

        Name  Age     city
0  Kulvinder   26   Lahore
1      Herry   33  Reading
2       Jack   24   London

In [191]:
## Accessing data from data frame
df["Name"] # it becomes series
type(df["Name"])

pandas.core.series.Series

In [192]:
df.loc[2]["Age"]

np.int64(24)

In [193]:
df.iloc[2]["city"]

'London'

In [194]:
# df['Name']

In [195]:
df.at[2,"Age"]

np.int64(24)

In [196]:
df.iat[1,2]

'Reading'

In [197]:
# Data Frame mainupulation
df["Salary"]=[50000,60000,70000]
df

        Name  Age     city  Salary
0  Kulvinder   26   Lahore   50000
1      Herry   33  Reading   60000
2       Jack   24   London   70000

In [198]:
# Remove colom
df.drop("Salary", axis=1, inplace=True)

In [199]:
df

        Name  Age     city
0  Kulvinder   26   Lahore
1      Herry   33  Reading
2       Jack   24   London

In [200]:
# Add Age to coloun
df["Age"]=df["Age"]+1
df

        Name  Age     city
0  Kulvinder   27   Lahore
1      Herry   34  Reading
2       Jack   25   London

In [201]:
df.drop(0,inplace=True)
df

    Name  Age     city
1  Herry   34  Reading
2   Jack   25   London

In [202]:
# datatype
print("Data Types: ", df.dtypes)
# describe dataframe
print("Statestical summary: ", df.describe())

Data Types:  Name    object
Age      int64
city    object
dtype: object
Statestical summary:               Age
count   2.000000
mean   29.500000
std     6.363961
min    25.000000
25%    27.250000
50%    29.500000
75%    31.750000
max    34.000000

    Name  Age     city
1  Herry   34  Reading
2   Jack   25   London